# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Uncomment the following line to enable the OLED Display
#CONFIG_ZMK_DISPLAY=y
#If battery widget is enabled, show percentage instead of icons
#CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
#Enable a widget to show words per minute
#CONFIG_ZMK_WIDGET_WPM_STATUS=y
